Rewrite GnuTLS and Crypto patches from Gentoo
This is a combination of work from two patches, backing out an earlier
change I did to have different options determingin if libcrypto was
compiled in and which SSL library you wished to support.  The method in
the patches from Gentoo was cleaner.  Since the people who submitted the
patch were from Debian, I probably got a bit carried away with an
earlier problem that I was experiencing.

Gentoo patch notes for 0060_all_opessl_crypto.patch

    Fix linking error:

    Undefined symbols:
      "_X509_free", referenced from:
          _smtp_open in ssmtp.o
    ld: symbol(s) not found

Gentoo patch notes for 0080_all_gnutls.patch

    http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=374327

    GPL code linked against OpenSSL without exception

    [ Alejandro Rios ]
    * Initial port from openssl to gnutls

    [ Anibal Monsalve Salazar ]
    * configure: replaced -lssl with /usr/lib/libgnutls-openssl.so.
    * ssmtp.c: replaced SSL_CTX_use_certificate_chain_file with
      SSL_CTX_use_certificate_file and marked SSL_CTX_check_private_key
      as not used.

    Alejandro Rios <alerios@debian.org>
    Anibal Monsalve Salazar <anibal@debian.org>

Gentoo patch 0060_all_opessl_crypto.patch and 0080_all_gnutls.patch